name = "LatticeFFTs"
uuid = "83e9f648-131d-4a3c-a1de-d155351cd207"
authors = ["Nils Niggemann <nils.niggemann@fu-berlin.de>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
